### ISSUE TITLE
Identify work issues from old lab content

### ISSUE THREAD

**Issue by scollier** [dustymabe/summit-2017-container-lab#1]
need to read through old lab guide and just figure out what some of the differences are, and create a work list based off of that.

**Comment by tchughesiv** [comment]
I haven't yet tested this work in the lab or w/ minishift... these are just things to discuss as possible changes / work items.

- Continue existing chapter reviews
    - Chapter 0 - https://github.com/dustymabe/summit-2017-container-lab/issues/11
        - move from CDK to minishift - reference dusty's work in https://github.com/dustymabe/summit-2017-container-lab/issues/16 & https://github.com/dustymabe/summit-2017-container-lab/issues/2
        - ~~may not be necessary for just pulls, test first... add newly deployed docker registry as an allowed (insecure?) registry in minishift docker config~~
    - Chapters 1-3 - https://github.com/dustymabe/summit-2017-container-lab/issues/9
        - ~~decide on root vs non-root images in ch. 3 - this impacts on how we configure "myproject" space in minishift & how we handle chapter 4.  Do we use anyuid or the default scc config.~~ No time this year...
            - ~~nice-to-have?~~
            - ~~there's a lot to be said for pushing users towards non-root images and restricted scc.~~
            - ~~if we go w/ non-root, some apps are easier than others to convert. must leverage different port for apache, for example.~~
        - ~~is custom.repo during image builds necessary? instead can we leverage the host's repos and yum-config-manager?~~ Still required since no sat server available locally this year.
        - ~~is :Z now the prefered method for "docker run" volumes in ch 3... instead of chcon? should be fully functional in 1.12.x ... worth testing?~~
            - ~~http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/~~
        - ~~Change references to LABELs to lowercase. e.g. RUN becomes run.~~
- Chapter 4 review
    - ~~move from cdk to minishift~~
    - ~~if using non-root wordpress image w/ different port, change docs and service to reflect the change.~~
    - use openshift to handle wordpress build as extra credit?
- Chapter 5 ??
    - ~~instead of creating service manually... let openshift handle it? should make things easier on user. 2 different ways to approach:~~
        - ~~oc new-app <image-url> (should create DC & Service) - probably easiest/best option~~
            - ~~e.g. oc new-app rhel-cdk.example.com:5000/wordpress~~
    - ~~Make the switch to the built-in mariadb template from SCL?~~
        - ~~show users they don't have to build their own.  Just deploy MariaDB already packaged w/ OpenShift.~~
            - ~~ephemeral option available out-of-the-box w/ minishift. maybe we add persistent template to image?~~
                - ~~oc get templates -n openshift | grep -i mariadb~~
