### ISSUE TITLE
investigate pushing to openshift registry instead of the registry we start early in the lab

### ISSUE THREAD

**Issue by dustymabe** [dustymabe/summit-2017-container-lab#10]

**Comment by tchughesiv** [comment]
Using the built-in build tools, this is a simple process.  I'll investigate next what it might look like to expose the minishift registry to the host for a docker push, if we even need to go there... if leveraging Minishift maybe no point in an external reg for docker push?

```bash
# Build/deploy directly from template in github
# first build takes some time... mostly around rhel7 image pull/extract... future builds much quicker.
oc new-app https://raw.githubusercontent.com/RHsyseng/container-rhel-examples/master/starter-arbitrary-uid/uid-ocp-template.yaml
oc logs -f bc/starter-arbitrary-uid
oc describe is/starter-arbitrary-uid
oc logs dc/starter-arbitrary-uid
```

OR

```bash
# Local builds are very doable w/ minishift.
# e.g. starting from the git repo base dir
cd ~/summit-2017-container-lab/
oc new-build . --name=bigimg --context-dir="labs/lab2/bigapp"
oc logs -f bc/bigimg

# future dev/mods can be triggered from local changes, like this:
# stop current build if still in progress
oc cancel-build bc/bigimg
cd ~/summit-2017-container-lab/
oc start-build bigimg --from-dir=.
oc logs -f bc/bigimg
oc describe is/bigimg

oc new-app bigimg
oc logs -f dc/bigimg
oc expose svc/bigimg
```

**Comment by dustymabe** [comment]
I tried last night to both "use the docker daemon running in minishift" as well as "expose the openshift registry so that we can push  to it". I used the docker daemon running in minishift just fine, but exposing the openshift registry was difficult and I was not able to pull it off.

**Comment by dustymabe** [comment]
short conclusion - we are going to go forward with starting our own registry and we can choose to use this registry at a later time if we somehow figure it out. Marking as nice-to-have

**Comment by dustymabe** [comment]
not going to do this
