### ISSUE TITLE
Rewrite lab 0 to reflect the new cdk

### ISSUE THREAD

**Issue by langdon** [dustymabe/summit-2017-container-lab#19]
Pretty much all of cdk has changed, vagrant, minishift, etc. We should just rewrite this intro.

**Comment by dustymabe** [comment]
@whitel - here is what I have:

workstation.example.com == labvm, the kvm machine that contains minishift and the atomic host
cdk.example.com == minishift host after it has been started
atomic-host.example.com == atomic host (running openshift) after it has been started 

These will be all populated in `/etc/hosts` on the labvm, some of them are now.

**Comment by dustymabe** [comment]
mostly done i guess
