### ISSUE TITLE
create repo vm

### ISSUE THREAD

**Issue by scollier** [dustymabe/summit-2017-container-lab#22]
I need to take the repo work that was done in previous issue, move that to VM, give that to @dustymabe

**Comment by scollier** [comment]
installed a RHEL 7.3 host on a new 100GB partition. host is called summit-2017-rhel-repo-vm....

sent IP address via email.

need to copy all the content over. and configure httpd, etc..

**Comment by scollier** [comment]
@dustymabe it's all done now.  I had to change the ip adderss. Check the /etc/yum.repos.d/summit-2017-lab.repo file for latest info.

**Comment by dustymabe** [comment]
this is done
