### ISSUE TITLE
figure out what to do about volume mounts

### ISSUE THREAD

**Issue by dustymabe** [dustymabe/summit-2017-container-lab#24]
if we use the docker that is in minishift then the "persistent volume" mounts from the host are no longer going to work. We can `minishift ssh` into the minishift vm and create them, but that might defeat the point of trying to explain to the user that we are using persistent volumes so that data doesn't get lost, since minishift is itself somewhat ephemeral. 

Here is the section we would have to change: https://github.com/dustymabe/summit-2017-container-lab/blame/master/labs/lab3/chapter3.md#L206-L213 

Thoughts?

**Comment by tchughesiv** [comment]
hmm, I'm going to submit a PR doing "minishift ssh" commands... I think its better than not demoing volumes at all.  up to the team though...
