### ISSUE TITLE
minishift launch error

### ISSUE THREAD

**Issue by langdon** [dustymabe/summit-2017-container-lab#33]
When I launched minishift in the VM following the instructions in /root/dusty/README.md, I got: 
```
E0403 17:41:23.247279   18552 start.go:192] Error adding developer user to sudoers exit status 1
```
Is this something i should tell people to ignore in LAB-0?

**Comment by scollier** [comment]
confirmed during my run-through.

**Comment by tchughesiv** [comment]
wasn't an issue for me last couple times i ran through the lab.
