### ISSUE TITLE
chp 1. docker wasn't started

### ISSUE THREAD

**Issue by scollier** [dustymabe/summit-2017-container-lab#37]
ran into:

$ sudo systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: http://docs.docker.com

during chapter 1. I was able to start it manually.

**Comment by dustymabe** [comment]
we actually aren't starting docker on the "host" but re-using what is inside minishift. we do have docker "installed" on the host so that we can use the docker client to talk to the docker that is inside minishift. does that make sense? 

feel free to update lab manual accordingly

**Comment by scollier** [comment]
that does.  i did start docker and there were no issues.  i'll run through it again and I won't start docker.  then I'll update the guide.

**Comment by scollier** [comment]
fixed by #46
