### ISSUE TITLE
chp 1. bad path

### ISSUE THREAD

**Issue by scollier** [dustymabe/summit-2017-container-lab#39]
error:

$ cd ~/labs/lab1
-bash: cd: /home/student/labs/lab1: No such file or directory
[student@localhost ~]$ cat Dockerfile
cat: Dockerfile: No such file or directory

path is actually:

/home/student/summit-2017-container-lab/labs/lab1

**Comment by dustymabe** [comment]
yep, i think we will just make sure that we address this and move the "content" of the lab to the "right path" for lab day. In other words, I think for clarity we should leave the path what it is (since it is probably least confusing to lab participants) and we'll make it the right path on lab day.

**Comment by scollier** [comment]
ack, i'll leave this open as a reminder, but take no action for now.

**Comment by tchughesiv** [comment]
here's the fix... we need to modify the /usr/local/bin/getlab script to look like this:
```shell
#!/bin/bash
# Grab from https://github.com/dustymabe/summit-2017-container-lab 
mkdir -p ~/summit-2017-container-lab
cd ~/summit-2017-container-lab
curl -L https://github.com/dustymabe/summit-2017-container-lab/archive/master.tar.gz | tar -xz --exclude='misc' --exclude='updateyumrepos.sh' --strip-components 1
```

**Comment by dustymabe** [comment]
why do we need to do that? the lab says `cd ~/labs/lab1`.

**Comment by tchughesiv** [comment]
the minishift walkthrough section in chapter0 says:
```shell
$ cd ~/summit-2017-container-lab
```
also, we tell folks at home to use git clone which would place the lab in the same ~/summit-2017-container-lab

**Comment by dustymabe** [comment]
`cd ~/labs/ ` is a lot easier than `cd ~/summit-2017-container-lab/labs/` but that is just my opinion.

I don't disagree about the "at home" case, but we can just give the "at home" people a different command to run to get the same effect if we wanted to.

**Comment by tchughesiv** [comment]
agree... was just taking cues from the ch0 work... thought its what the team wanted universally. so, does @whitel need to mod ch0 as well?

**Comment by tchughesiv** [comment]
also, do we care about the at home workers getting confused?

**Comment by tchughesiv** [comment]
someone give me a path and we'll modify the lab content to match.  i don't like having different paths for different students though, probably unecessary.

**Comment by dustymabe** [comment]
ehh - if you like `summit-2017-container-lab` then that's fine. there are probably a lot of places that need updating, though.

**Comment by tchughesiv** [comment]
i don't necessarily "like" it... just don't like having different instructions for "at-home" folks.  let's roll w/ this and see how it works i guess.

**Comment by tchughesiv** [comment]
how do we modify the getlab script though @dustymabe ? is that in the image?

**Comment by dustymabe** [comment]
it's in the image, but we are going to update it on the day of the lab anyway to pull the lab content from the instructor machine. assuming I don't have to build another image then we'll just sort it out on the day of the lab

**Comment by tchughesiv** [comment]
k

**Comment by tchughesiv** [comment]
i've added a milestone date of 5/1 to this so we remember to update the getlab script accordingly before the lab starts... this will address our pathing issues.  I'm also adding a manual note to dusty's README on the host.

**Comment by tchughesiv** [comment]
getlab replacement:
```shell
# replace existing getlab script
su -
cat <<EOF > /usr/local/bin/getlab
#!/bin/bash
# Grab from https://github.com/dustymabe/summit-2017-container-lab
cd ~/ && git clone https://github.com/dustymabe/summit-2017-container-lab
EOF
exit
```

**Comment by dustymabe** [comment]
on 5/1 getlab will look more like `rsync from instructor machine to local machine` :)

**Comment by scollier** [comment]
fixed.
