### ISSUE TITLE
chp 1. nsenter broke

### ISSUE THREAD

**Issue by scollier** [dustymabe/summit-2017-container-lab#40]
error:

[student@localhost lab1]$ docker inspect --format '{{ .State.Pid }}' apache
16149
[student@localhost lab1]$ nsenter -m -u -n -i -p -t 16149
nsenter: cannot open /proc/16149/ns/ipc: No such file or directory

docker exec -it ... worked.

**Comment by dustymabe** [comment]
since we are using docker from minishift I don't think we can use nsenter any longer unless we `minishift ssh` into the minishift VM. using docker exec here is fine or minishift ssh into the VM is fine.

**Comment by scollier** [comment]
will remove.

**Comment by scollier** [comment]
fixed by #45
