### ISSUE TITLE
chp 2. bad path

### ISSUE THREAD

**Issue by scollier** [dustymabe/summit-2017-container-lab#41]
same error as chapter 1 for dir structure:

$ cd ~/labs/lab2/bigapp/
-bash: cd: /home/student/labs/lab2/bigapp/: No such file or directory

need to clone repo into right name, or change path.

**Comment by scollier** [comment]
same as #39 will leave this open, no action for now.  just a reminder.

**Comment by tchughesiv** [comment]
fix should be applied as stated in https://github.com/dustymabe/summit-2017-container-lab/issues/39

**Comment by tchughesiv** [comment]
fixed w/ https://github.com/dustymabe/summit-2017-container-lab/pull/68 & https://github.com/dustymabe/summit-2017-container-lab/issues/64
