### ISSUE TITLE
chp 2. port

### ISSUE THREAD

**Issue by scollier** [dustymabe/summit-2017-container-lab#42]
```
$ docker port bigapp 80
Error: No public port '80/tcp' published for bigapp
```

change:

docker port bigapp 80 to 1080 in doc.

**Comment by dustymabe** [comment]
should be `1080`

**Comment by dustymabe** [comment]
actually it should be `80`, so it is right. See https://github.com/dustymabe/summit-2017-container-lab/issues/43#issuecomment-292019867
