### ISSUE TITLE
ch. 1 - root not necessary

### ISSUE THREAD

**Issue by tchughesiv** [dustymabe/summit-2017-container-lab#47]
This line unecessary:
_Perform the following commands as root unless instructed otherwise._
https://github.com/dustymabe/summit-2017-container-lab/blob/691f87bd5352242b71dda49723ca971bed1d0ac1/labs/lab1/chapter1.md

Root is not required and, if anything, causes issues w/ the lab.  The docker client can't connect as root.

Sudo also shouldn't be necessary, but maybe makes sense left in?
```sudo systemctl status docker```

**Comment by dustymabe** [comment]
feel free to clean up mentions of root.

**Comment by tchughesiv** [comment]
fixed w/ https://github.com/dustymabe/summit-2017-container-lab/pull/53
