### ISSUE TITLE
remove "workstation.example.com" mentions

### ISSUE THREAD

**Issue by tchughesiv** [dustymabe/summit-2017-container-lab#50]
remove "workstation.example.com" mentions from start of each lab... unless we intend to leverage this hostname somehow?

**Comment by dustymabe** [comment]
yeah i think that's what we'll call the labvm maybe - didn't know what else to call it

**Comment by dustymabe** [comment]
the updated environment now has workstation.example.com as the hostname

**Comment by tchughesiv** [comment]
keeping
