### ISSUE TITLE
ch. 2 best practice references

### ISSUE THREAD

**Issue by tchughesiv** [dustymabe/summit-2017-container-lab#52]
In the following section at the end of ch. 2, a couple of items either need to be properly "fixed" in ch. 3 like we say we will demonstrate... or removed from this section of ch. 2 entirely. Specifically these two items:

* Use a specific tag for the source image. Image updates may break things.
* Avoid running application as root user.

We can fix the "tag" item w/ something like the following in ch. 3:
```Dockerfile
FROM registry.access.redhat.com/rhel7:7.3-74
```
For the non-root container, we'd potentially have to make quite a few mods to our ch. 3 Dockerfiles.

-------------------------
https://github.com/dustymabe/summit-2017-container-lab/blob/9db62fd9c9c2311053b7726df5e60e945e84bb57/labs/lab2/chapter2.md#review-dockerfile-practices
```markdown
More generally:

* Use a specific tag for the source image. Image updates may break things.
* Place rarely changing statements towards the top of the file. This allows the re-use of cached image layers when rebuilding.
* Group statements into multi-line statements. This avoids layers that have files needed only for build.
* Use `LABEL RUN` instruction to prescribe how the image is to be run.
* Avoid running application as root user.
* Use `VOLUME` instruction to create a host mount point for persistent storage.

In the next lab we will fix these issues and break the application up into separate services.
```

**Comment by dustymabe** [comment]
> Use a specific tag for the source image. Image updates may break things.
> Avoid running application as root user.

I agree we can "fix" the tag item pretty trivially. 

As far as running as non-root, the application we have doesn't lend itself well to that. I don't think we have to remove the guidance even if we don't take our own advice here. Would be nice if we did, but we are kinda out of time for making large changes.

**Comment by tchughesiv** [comment]
image tag addressed w/ https://github.com/dustymabe/summit-2017-container-lab/pull/62

may look into addressing non-root... leaving open in case there's time.
