### ISSUE TITLE
lab1: clean up revisit docker section in the context of minishift.

### ISSUE THREAD

**Issue by dustymabe** [dustymabe/summit-2017-container-lab#57]
in 3b0b76b i added some clarification about using minishift docker-env to access minishift's docker - lets clean up this whole "revisit docker" section and make it make sense in terms of minishift.

**Comment by dustymabe** [comment]
@scollier @tchughesiv - want to take this one?

**Comment by tchughesiv** [comment]
question to answer w/ this issue:
_when we are exporing dockers files like cat /usr/lib/systemd/system/docker.service does it make sense to do this on the labvm or within minishift?_

**Comment by dustymabe** [comment]
i don't really think it makes sense to do this on the labvm, since we aren't using that docker. maybe we should `minishift ssh` in and browse around. The only problem with this is that the minishift environment (booted live-cd) might be confusing as well. Why don't you browse around and see how similar it is to what we had in the past?

**Comment by tchughesiv** [comment]
mostly addressed w/ https://github.com/dustymabe/summit-2017-container-lab/pull/67

still discussing docker config file views
