### ISSUE TITLE
where to start labs

### ISSUE THREAD

**Issue by tchughesiv** [dustymabe/summit-2017-container-lab#64]
based on my testing, we need to be sure we start our lab0 after the following has been done in @dustymabe 's README.

```shell
# start the VM
export user=yourname
./recycle2.sh 

# Find IP of VM (wait some time and then run)
virsh domifaddr 2017labvm-$user

# ssh in
# user: student pass: student
# user: root    pass: redhat
ssh student@ip
```

the rest of the README is done in lab0. I'll edit the README accordingly.

**Comment by tchughesiv** [comment]
this also means that the above needs to have already taken place for our students before they start the lab.

**Comment by dustymabe** [comment]
@whitel - any progress on lab0?

**Comment by tchughesiv** [comment]
new dusty/README looks like this:

```shell
# start the VM
export user=yourname
./recycle2.sh 

# Find IP of VM (wait some time and then run)
virsh domifaddr 2017labvm-$user

# ssh in
# user: student pass: student
# user: root    pass: redhat
ssh student@ip

# replace existing getlab script
cat <<EOF > /usr/local/bin/getlab
#!/bin/bash
# Grab from https://github.com/dustymabe/summit-2017-container-lab 
mkdir -p ~/summit-2017-container-lab
cd ~/summit-2017-container-lab
curl -L https://github.com/dustymabe/summit-2017-container-lab/archive/master.tar.gz | tar -xz --exclude='misc' --exclude='updateyumrepos.sh' --strip-components 1
EOF

################
REFERENCE chapter 0 starting here...
https://github.com/dustymabe/summit-2017-container-lab/blob/master/labs/lab0/chapter0.md
```

**Comment by dustymabe** [comment]
hmm - you should just `cd ~/ && git clone https://github.com/dustymabe/summit-2017-container-lab`

**Comment by tchughesiv** [comment]
but, don't we want getlab script referenced in lab0 to work for students?

**Comment by dustymabe** [comment]
sure, but what I'm saying is that your suggested `getlab` replacement script is too complicated. it can be done in fewer steps.

**Comment by tchughesiv** [comment]
oh ya... agreed... but i assumed we wanted to keep the existing logic that was there historically as it removes certain folders/files from the repo?

here's the full curl:
curl -L https://github.com/dustymabe/summit-2017-container-lab/archive/master.tar.gz | tar -xz --exclude='misc' --exclude='updateyumrepos.sh' --strip-components 1

**Comment by dustymabe** [comment]
> oh ya... agreed... but i assumed we wanted to keep the existing logic that was there historically as it removes certain folders/files from the repo?

that was only done so that we just pulled the `labs` directory out of the tarball so that we could `cd ~/labs/`. if we are going to this new model then just do a simple `git clone`.

**Comment by tchughesiv** [comment]
ok

**Comment by tchughesiv** [comment]
done... new README
```shell
# start the VM
export user=yourname
./recycle2.sh 

# Find IP of VM (wait some time and then run)
virsh domifaddr 2017labvm-$user

# ssh in
# user: student pass: student
# user: root    pass: redhat
ssh student@ip

# replace existing getlab script
su -
cat <<EOF > /usr/local/bin/getlab
#!/bin/bash
# Grab from https://github.com/dustymabe/summit-2017-container-lab
cd ~/ && git clone https://github.com/dustymabe/summit-2017-container-lab
EOF
exit

################
REFERENCE chapter 0 starting here...
https://github.com/dustymabe/summit-2017-container-lab/blob/master/labs/lab0/chapter0.md
```

**Comment by dustymabe** [comment]
looks good

**Comment by scollier** [comment]
great summary @tchughesiv, got me started.

**Comment by dustymabe** [comment]
i think we're done with this.
