### ISSUE TITLE
chapter 3 formatting issue

### ISSUE THREAD

**Issue by scollier** [dustymabe/summit-2017-container-lab#74]
There's a stanza after this option:

-p <host_port>:<container_port> to map the container port to the host port

That has some minishift commands.  There is no setup for the commands to say why you are running them, and they are indented after a command option. It's simply a formatting issue.

It happens again right below it with another stanza of commands that are not formatted:

    --link <name>:<alias> to link to the database container

        minishift ssh "ls -lZd /var/lib/wp_uploads"
        docker run -d -v /var/lib/wp_uploads:/var/www/html/wp-content:Z -p 1080:80 --link mariadb:db --name wordpress wordpress
        # Note the difference in SELinux context after running w/ a volume & :Z.
        minishift ssh "ls -lZd /var/lib/wp_uploads"
        docker logs $(docker ps -ql)
        minishift ssh "ls -l /var/lib/wp_uploads"
        docker ps
        curl -L http://cdk.example.com:1080

**Comment by dustymabe** [comment]
i think this was intentional

**Comment by scollier** [comment]
fixed #82
