### ISSUE TITLE
review chapters 1-3

### ISSUE THREAD

**Issue by scollier** [dustymabe/summit-2017-container-lab#9]

**Comment by scollier** [comment]
Skipped chapter 0

Chapter 1 review:

1. couldn't cd into vagrantcdklab directory
2. I had to remove the custom repo when building the apache image, cause it points to a local repo that I don't have.  Same thing with registry.
3. Rest of the commands look OK.

**Comment by scollier** [comment]
Chapter 2 review:
Building bigimg results in openssl package conflicts:

To enable this functionality please set 'notify_only=0' in /etc/yum/pluginconf.d/search-disabled-repos.conf
**********************************************************************

 You could try using --skip-broken to work around the problem
Error: Package: 1:openssl-1.0.1e-60.el7.x86_64 (rhel-7-server-rpms)
           Requires: openssl-libs(x86-64) = 1:1.0.1e-60.el7
           Installed: 1:openssl-libs-1.0.1e-60.el7_3.1.x86_64 (@anaconda/7.3)
               openssl-libs(x86-64) = 1:1.0.1e-60.el7_3.1
           Available: 1:openssl-libs-1.0.1e-34.el7.x86_64 (rhel-7-server-rpms)
               openssl-libs(x86-64) = 1:1.0.1e-34.el7
           Available: 1:openssl-libs-1.0.1e-34.el7_0.3.x86_64 (rhel-7-server-rpms)

**Comment by tchughesiv** [comment]
Chapter 1 review:

I think the apache Dockerfile could use some tweaks to more closely follow "good practice".  For starters, consildating the RUN commands. Something like the following, with the understanding that we'll need to modify slightly for custom repo use.

```Dockerfile
FROM registry.access.redhat.com/rhel7
MAINTAINER Student <student@foo.io>

# Simple startup script to avoid some issues observed with container restart 
ADD run-apache.sh /run-apache.sh
# ADD ./custom.repo /etc/yum.repos.d/custom.repo
RUN yum clean all && yum-config-manager --disable \* &> /dev/null && \
    yum-config-manager --enable rhel-7-server-rpms && \
    yum -y update-minimal --security --sec-severity=Important --sec-severity=Critical --setopt=tsflags=nodocs && \
    yum -y install --setopt=tsflags=nodocs httpd && \
    yum clean all && \
    echo "Apache" >> /var/www/html/index.html && \
    echo 'PS1="[apache]#  "' > /etc/profile.d/ps1.sh && \
    chmod -v +x /run-apache.sh

EXPOSE 80
CMD [ "/run-apache.sh" ]
```

Additionally, I think it might be good to start encouraging non-root image builds?  But maybe we save that for the labs 2-4?

**Comment by dustymabe** [comment]
> For starters, consildating the RUN commands.

I think we start with "good practice" stuff in a later lab. So we take this file and modify it to more closely match good practice, teaching along the way.

**Comment by tchughesiv** [comment]
@scollier that openssl install issue appears to be related to stale repo data... maybe from sat6?  Leveraging minishift for the build instead, against cdn, builds correctly.

Chapter 2 review:

Proposed Dockerfile edits (pre custom.repo):
```Dockerfile
FROM registry.access.redhat.com/rhel7
MAINTAINER Student <student@foo.io>

# COPY set up scripts
COPY scripts /scripts
# Add in wordpress sources 
COPY latest.tar.gz /latest.tar.gz
# COPY ./custom.repo /etc/yum.repos.d/custom.repo
RUN yum clean all && yum-config-manager --disable \* &> /dev/null && \
    yum-config-manager --enable rhel-7-server-rpms && \
    yum -y update-minimal --security --sec-severity=Important --sec-severity=Critical --setopt=tsflags=nodocs && \
    yum -y install --setopt=tsflags=nodocs httpd \
        openssl \
        procps-ng \
        psmisc \
        php \
        php-mysql \
        php-gd \
        tar \
        mariadb-server \
        net-tools \
        hostname && \
    yum clean all && \
    tar xvzf /latest.tar.gz -C /var/www/html --strip-components=1 && \
    rm /latest.tar.gz && \
    chown -R apache:apache /var/www/ && \
    chmod 755 /scripts/*

EXPOSE 80
CMD ["/bin/bash", "/scripts/start.sh"]
```

Addt'l thoughts, when do we want to bring in an openshift build/deploy? this lab or later? or do we at all?
In order to make this work in Minishift, we'll have to increase scc rights to anyuid because this image is pretty reliant on root as-is.  OR, i can try to make this work w/ non-root user... but it'll add a little more complexity to the image.

MiniShift build notes:
```bash
# OpenShift builds are very doable w/ minishift.
# e.g. starting from the git repo base dir
cd ~/summit-2017-container-lab/
oc new-build . --name=bigimg --context-dir="labs/lab2/bigapp" --strategy=docker
oc logs -f bc/bigimg

# future dev/mods can be triggered from local changes, like this:
# stop current build if still in progress
oc cancel-build bc/bigimg
cd ~/summit-2017-container-lab/
oc start-build bigimg --from-dir=.
oc logs -f bc/bigimg
```

MiniShift deploy notes, if we decided to give everyone anyuid (which i think we did in last year's lab):
```bash
oc new-app bigimg
oc logs -f dc/bigimg
oc expose svc/bigimg
```

Thoughts? anyuid access isn't encouraging best practice and will continue to confuse folks who attempt similar deploys in OpenShift Online/Dedicated/etc.

**Comment by scollier** [comment]
@tchughesiv thanks.  I will register that host with CDN and test again.

**Comment by dustymabe** [comment]
ok @scollier @tchughesiv - i've got the new environment in place and updated the lab md files with some fixups. please follow /root/dusty/README.md for instructions on how to get the lab env up and running and then start on lab1 and go from there. Lots of little fixups needed, but mostly just to make things "correct". Most of what is there now should be functional.

**Comment by dustymabe** [comment]
@whitel ^^

**Comment by scollier** [comment]
ran into:

```
$ sudo systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: http://docs.docker.com
``` 

during chapter 1.

**Comment by scollier** [comment]
Looks like a typo:

##Let's explore a Dockerfile

**Comment by scollier** [comment]
error:

```
$ cd ~/labs/lab1
-bash: cd: /home/student/labs/lab1: No such file or directory
[student@localhost ~]$ cat Dockerfile
cat: Dockerfile: No such file or directory
```

**Comment by scollier** [comment]
typo:

contianer

**Comment by scollier** [comment]
error:

```
$ curl http://cdk.example.com:1080
curl: (7) Failed connect to cdk.example.com:1080; Connection refused
```

**Comment by scollier** [comment]
error:

```
[student@localhost lab1]$ docker inspect --format '{{ .State.Pid }}' apache
16149
[student@localhost lab1]$ nsenter -m -u -n -i -p -t 16149
nsenter: cannot open /proc/16149/ns/ipc: No such file or directory
```

**Comment by scollier** [comment]
same error as chapter 1 for dir structure:

```
$ cd ~/labs/lab2/bigapp/
-bash: cd: /home/student/labs/lab2/bigapp/: No such file or directory
```
need to clone repo into right name, or change path.
